<script>

const DEPT_OPD_DISEASE = 'opd_disease'
const DEPT_METHADONE_PHARMACIST = 'methadone_pharmacist'
const DEPT_BLOOD_TAKING = 'blood_taking'
const DEPT_WOUND_CARE = 'wound_care'
const DEPT_FUNDOSCOPY = 'fundoscopy'
const DEPT_XRAY = 'x-ray'
const DEPT_DIET_COUNSELLING = 'diet_counselling'
const DEPT_PREMARITAL_SCREENING = 'premarital_screening'
const DEPT_MEDICAL_CHECKUP = 'medical_checkup'
const DEPT_ANTENATAL = 'antenatal'
const DEPT_POSTNATAL = 'postnatal'
const DEPT_FAMILY_PLANNING = 'family_planning'
const DEPT_PAP_SMEAR = 'pap_smear'
const DEPT_IMMUNIZATION = 'immunization'

const DEPT_ALL = [
  DEPT_OPD_DISEASE,
  DEPT_METHADONE_PHARMACIST,
  DEPT_BLOOD_TAKING,
  DEPT_WOUND_CARE,
  DEPT_FUNDOSCOPY,
  DEPT_XRAY,
  DEPT_DIET_COUNSELLING,
  DEPT_PREMARITAL_SCREENING,
  DEPT_MEDICAL_CHECKUP,
  DEPT_ANTENATAL,
  DEPT_POSTNATAL,
  DEPT_FAMILY_PLANNING,
  DEPT_PAP_SMEAR,
  DEPT_IMMUNIZATION
]

module.exports = {
  DEPT_ALL,
  DEPT_OPD_DISEASE,
  DEPT_METHADONE_PHARMACIST,
  DEPT_BLOOD_TAKING,
  DEPT_WOUND_CARE,
  DEPT_FUNDOSCOPY,
  DEPT_XRAY,
  DEPT_DIET_COUNSELLING,
  DEPT_PREMARITAL_SCREENING,
  DEPT_MEDICAL_CHECKUP,
  DEPT_ANTENATAL,
  DEPT_POSTNATAL,
  DEPT_FAMILY_PLANNING,
  DEPT_PAP_SMEAR,
  DEPT_IMMUNIZATION
}

</script>
